---
title: "Finally got a site up"
date: 2018-07-30
tags: ["blogging", "data science"]
---

# Consider it an early birthday present to myself.

While my summer courseload is winding down, I wanted to spend some time putting together a site. Most folks in the data science community suggest some type of presence - partially for visibility, but mostly to get your thoughts and projects in one place. I've done my fair share of googling how-to-do-this-thing-in-R, so it's about time I contribute back.


I've got an applied math degree from the University of Michigan and am currently enrolled in a relatively new data science program at Grand Valley State University. Between schooling, I've been an analyst at Wolverine World Wide, formally on the sales side of the business, but getting my toes wet with Finance, Marketing, and Product Development groups. I've been fortunate enough to get a DataCamp subscription, which propelled my understanding of R and the data science field in general. 


Please reach out! I'd love to chat.